services:
   cloudbeaver:
    hostname: cloudbeaver
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    ports:
      - "8978:8978" # Host_Port:Container_Port
    labels:
      "com.helios.target": "http://localhost:8978"
    environment:
      # Optional: Configure the initial admin user
      CB_ADMIN_NAME: cbadmin
      CB_ADMIN_PASSWORD: Abcd1234 # Change this to a secure password
      CB_SERVER_NAME: "Test Server"
      CB_SERVER_URL: "cloudbeaver.devlocal.site"
