services:
  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   volumes:
  #     - ./loki-config.yaml:/etc/loki/local-config.yaml
  #     - ../data/loki_data:/loki
  #   networks:
  #     - monitoring_network
  #   labels:
  #     "com.helios.target": "http://localhost:3100"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../data/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_DOMAIN=grafana.${DOMAIN}
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}/
      - GF_SERVER_PROTOCOL=https
      - GF_LIVE_ALLOWED_ORIGINS=grafana.${DOMAIN}
      - GF_SECURITY_CSRF_TRUSTED_ORIGINS=grafana.${DOMAIN}
    networks:
      - monitoring_network
    labels:
      "com.helios.target": "https://localhost:3000"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring_network
    labels:
      "com.helios.target": "http://localhost:9090"
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./node-exporter.yml:/etc/node_exporter/config.yml
      # - ./grafana/provisioning/:/etc/grafana/provisioning/
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.config.file=/etc/node_exporter/config.yml'
    networks:
      - monitoring_network
    ports:
      - 9100:9100
    labels:
      "com.helios.target": "http://localhost:9100"
  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - monitoring_network
    ports:
      - 9093:9093
    labels:
      "com.helios.target": "http://localhost:9093"

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring_network:
    driver: bridge
