# tls_server_config:
#   cert_file: /etc/node_exporter/node_exporter.crt # Optional: if using TLS
#   key_file: /etc/node_exporter/node_exporter.key # Optional: if using TLS
# basic_auth_users:
#   <USERNAME>: <HASHED-PASSWORD> # htpasswd -nBC 12 "" | tr -d ':\n'

