services:
  hue:
    image: "gethue/hue:latest"
    container_name: hue
    ports:
      - "8888:8888"
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    labels:
      "com.helios.target": "http://localhost:8888"
